version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # API 端口
      - "9001:9001"   # 控制台端口
    environment:
      MINIO_ROOT_USER: admin              # 管理员用户名
      MINIO_ROOT_PASSWORD: admin123       # 管理员密码（至少8位）
    volumes:
      - /opt/minio/data:/data              # 持久化数据
      - /opt/minio/config:/root/.minio     # 持久化配置
    command: server /data --console-address ":9001"
    restart: always
