version: '3.8'
services:
  mysql3:
    image: mysql:8.0
    container_name: mysql3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "33063:3306"
    volumes:
      - mysql3-data:/develop/mysql/mysql3
      - /develop/mysql/config/mysql3.cnf:/etc/mysql/conf.d/custom.cnf # 挂载到conf.d目录下并命名为.cnf结尾  # 挂载自定义的 my.cnf 文件
    networks:
      - mysql-cluster
volumes:
  mysql3-data:


networks:
  mysql-cluster:
    driver: bridge


