server:
  port: 8001

# mybatis配置
mybatis:
  type-aliases-package: com.example.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations:  classpath:mybatis/mapper/*.xml


# spring 配置

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456



#      config:
#        server-addr: 192.168.19.124:8848