server:
  port: 8002
  address: 0.0.0.0
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # 访问的端口为微服务的端口
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    use-root-path: true
  cache:
    disabled: true
#java:
#  net:
#    preferIPv4Stack: true

jwt:
  secret: 7CA6AFDA-B94C-4CCF-AC45-7C802BD0745F

# 用于表示将大文件上传至 minio
minio:
   url: http://192.168.19.121:9000
   access-key: minioadmin
   secret-key: minioadmin
   bucket-name: big-file