-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0xTDBGBBgWL4PVFD
ywYNzkbvbnFBlgP1DfgnWeN+OUagCgYIKoZIzj0DAQehRANCAAR5s0ya8JOYLiMA
bb2Ni2hJFTdCmwPJoN1DlIBCYatUIzfdtaSy6RuukUsS6QRzt6DBkOFi+nsiYQ1R
1J1/G8vK
-----END PRIVATE KEY-----