server:
  port: 8006

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs  # 访问的端口为微服务的端口
  swagger-ui:
    path: /swagger-ui.html
    tagsSorter: alpha
    use-root-path: true
  cache:
    disabled: true

#spring:
#  main:
#    web-application-type:
#      reactive

# 用于配置 spring security


spring:
  application:
    name: authorization-resource-server  # 服务名称
  # 服务名称+开发环境+文件后缀名 = nacos配置的Data Id
  profiles:
    active: mac   #开发环境
#  main:
#    web-application-type: reactive
#    allow-bean-definition-overriding: true

---
spring:
  config:
    activate:
      on-profile: mac
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.180:8848
        #        server-addr: 127.0.0.1:8848
        group: QD
        namespace: ec6c3694-b06e-4690-a632-b10748bde5b1
        #        namespace: 1b2b72d4-ca4b-48b1-a6ca-a8f17c27c547
        username: nacos
        password: nacos
        enable: true
      config:
        #        import-check:
        #          enabled: false
        server-addr: 192.168.22.180:8848
        #        server-addr: 127.0.0.1:8848
        group: QD   # 需要在nacos 的namespace中创建，名字为QD的Service
        #        namespace: bc73081d-7fca-422d-ba18-cfe2e62a2136 # 将QD的namespace中id填入
        namespace: ec6c3694-b06e-4690-a632-b10748bde5b1 # 将QD的namespace中id填入
        username: nacos
        password: nacos
        import-check:
          enabled: false
#        file-extension: yaml # 文件后缀名
#        enable: true
  ## 用于配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.22.180:3306/spring_cloud_db
    #    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db
    username: root
    password: 123456



#security:
#  ignored=/**:
#  enable-csrf: false

---
spring:
  config:
    activate:
      on-profile: windows
  cloud:
    nacos:
      discovery:
        #        server-addr: 192.168.19.121:8848
        server-addr: 127.0.0.1:8848
        group: QD
        #        namespace: bc73081d-7fca-422d-ba18-cfe2e62a2136
        namespace: 1b2b72d4-ca4b-48b1-a6ca-a8f17c27c547
        username: nacos
        password: nacos
        enable: true
      config:
        #        server-addr: 192.168.19.121:8848
        server-addr: 127.0.0.1:8848
        group: QD   # 需要在nacos 的namespace中创建，名字为QD的Service
        #        namespace: bc73081d-7fca-422d-ba18-cfe2e62a2136 # 将QD的namespace中id填入
        namespace: 1b2b72d4-ca4b-48b1-a6ca-a8f17c27c547 # 将QD的namespace中id填入
        username: nacos
        password: nacos
        file-extension: yaml # 文件后缀名
        enable: true
  ## 用于配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.19.121:3306/spring_cloud_db
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db
    username: root
    password: 123456