server:
  port: 8005



spring:
  application:
    name: order-server  # 服务名称
  # 服务名称+开发环境+文件后缀名 = nacos配置的Data Id
  profiles:
    active: mac   #开发环境
  main:
    web-application-type: servlet #reactive
    allow-bean-definition-overriding: true
  config:
    import:
      - optional:nacos:datasource.yml
      - optional:nacos:redis.yml
      - optional:nacos:springdoc.yml
      - optional:nacos:xxl-job.yml
      - optional:nacos:rabbitmq.yml
      - optional:nacos:elasticsearch.yml
      - optional:nacos:logging.yml

  #  Spring Boot Actuator 的配置，用于开放应用的运行状态监控接口。
  management:
    endpoints:
      web:
        exposure:
          include: health,metrics,beans,threaddump
      health:
        show-details: always
      metrics:
        enabled: true



  cloud:
    openfeign:
      okhttp:
        enabled: true
#      client:
#        config:
#          default: # 对所有FeignClient生效
#            loggerLevel: full
#      httpclient:
#        enabled: false
#        max-connections: 200  # 最大的连接数
#        max-connections-per-route: 50 # 每个路径的最大连接数
---
spring:
  config:
    activate:
      on-profile: mac
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.180:8848
        group: spring-cloud-example-dev
        namespace: cb500d3d-c86c-4230-8f7f-f5434caf711a
#        username: nacos
#        password: nacos
      #        enable: true
      config:
        server-addr: 192.168.22.180:8848
        group: spring-cloud-example-dev
        namespace: cb500d3d-c86c-4230-8f7f-f5434caf711a
#        username: nacos
#        password: nacos
        import-check:
          enabled: false
  #        file-extension: yaml # 文件后缀名
  #        enable: true
#security:
#  ignored=/**:
#  enable-csrf: false
