server:
  port: 8006


spring:
  application:
    name: seckill-server  # 服务名称
  # 服务名称+开发环境+文件后缀名 = nacos配置的Data Id
  profiles:
    active: mac   #开发环境
  main:
    web-application-type: servlet #reactive
    allow-bean-definition-overriding: true
  config:
    import:
#      - optional:nacos:datasource.yml
      - optional:nacos:redis.yml
      - optional:nacos:springdoc.yml
      - optional:nacos:logging.yml
      - optional:nacos:seckill-sentinel.yml
#  config:
#    import:
#      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml


---
spring:
  config:
    activate:
      on-profile: mac
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.22.180:8848
        group: spring-cloud-example-dev
        namespace: cb500d3d-c86c-4230-8f7f-f5434caf711a
#        username: nacos
#        password: nacos
        enable: true
      config:
        server-addr: 192.168.22.180:8848
        group: spring-cloud-example-dev
        namespace: cb500d3d-c86c-4230-8f7f-f5434caf711a
#        username: nacos
#        password: nacos
#        enable: true
        import-check:
          enabled: false
  #        file-extension: yaml # 文件后缀名

  ## 用于配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.22.180:3306/store
    #    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: druid@123
        allow: 127.0.0.1        # 白名单，多个使用逗号隔开（不在白名单中不能访问，默认开启localhost/127.0.0.1）
      filter:
        stat:
          enabled: true           # 启动SQL语句监控，同时会影响其他面板中的SQL展示（如：影响"URI监控"中的jdbc数据）
          db-type: mysql          # 数据库类型（实测没啥用，会自动根据上面的连接自动识别）

          log-slow-sql: true      # 记录慢日志（"SQL监控"面板中数值会标记为红色）
          slow-sql-millis: 3000   # 慢日志判定标准（单位：毫秒）
          slow-sql-log-level: ERROR # 自定义日志级别，默认日志级别"ERROR"


#security:
#  ignored=/**:
#  enable-csrf: false

